### ISSUE TITLE
ci: main allows merging stale branches, so semantic merge conflicts reach main untested

### ISSUE THREAD

**Issue by chopratejas** [chopratejas/headroom#3066]
## Problem

`main` does not require a PR branch to be up to date before merging. Branch protection currently reports:

```
required_status_checks.strict = false
required_approving_review_count = 0
```

So a PR can be approved and fully green against a base commit that is days old, merge cleanly, and break `main` — because no per-PR check can see an interaction with something that landed in the meantime.

## What this cost us

On 16 Aug, #3051 added `bind_scope(tags, request.scope)` at `headroom/proxy/handlers/gemini.py:325` and updated the three Gemini test fakes it knew about.

#3035 had branched earlier. It added a **fourth** `_FakeRequest`, without `.scope`.

Both PRs were green against their own bases. Git merged both without a textual conflict. On merged `main` the result is:

```
AttributeError: '_FakeRequest' object has no attribute 'scope'
```

This is a semantic merge conflict: no diff overlaps, so nothing flagged it. A rebase would have surfaced it immediately, because the test would have failed on the rebased branch.

Fixed in #3064, but the class of bug will recur.

## Why it matters more right now

Ten PRs merged on 16 Aug, several touching the same proxy handlers. Merge velocity is exactly when stale-base interactions get likely, and the current settings offer no protection at all.

## Suggested fix

Enable **"Require branches to be up to date before merging"** on `main` (`required_status_checks.strict = true`).

Trade-off, stated honestly: with a required-checks gate this forces a rebase-and-re-run for any PR whose base has moved, which slows a busy merge queue and can cause churn when many PRs land at once. GitHub's merge queue is the usual answer if that becomes painful.

Worth deciding alongside `required_approving_review_count`, which is currently `0` — note this is also why `reviewDecision` is `null` on every PR via the API, so tooling that keys off `reviewDecision` silently sees zero approvals even when reviews exist.

## Acceptance

- `main` requires branches to be current before merge, **or** a merge queue is enabled.
- A PR based on a stale commit cannot merge without re-running checks.

**Comment by Parideboy** [comment]
Still reproducible as of 24 Aug. I do not have admin on this repo, so `GET /repos/headroomlabs-ai/headroom/branches/main/protection` returns 404 for me and `branchProtectionRules` comes back empty. I checked the merge behaviour instead, which shows the same thing:

**Stale branches are still merging.** For each recently merged PR I compared the squash commit's parent (i.e. `main` at merge time) against the PR head:

| PR | merged | commits behind `main` at merge |
|----|--------|-------------------------------|
| #3146 | 21 Aug | 11 |
| #3144 | 21 Aug | 8 |
| #3145 | 21 Aug | 7 |
| #3149 | 21 Aug | 5 |
| #3212 | 22 Aug | 1 |

**Open PRs confirm `strict` is still false.** #3225 and #3224 both report `mergeStateStatus = CLEAN` while sitting behind `main`. GitHub only emits `BEHIND` when the base branch requires branches to be up to date, so `CLEAN` plus a non-zero `behind_by` is a direct read of the setting. #3192 is currently 13 commits behind and touches `headroom/proxy/server.py`, which `main` also changed in that window — the same shape as the #3051/#3035 breakage.

To reproduce for any open PR:

```bash
gh api "repos/headroomlabs-ai/headroom/compare/main...$(gh pr view <N> --json headRefOid --jq .headRefOid)" \
  --jq '{behind: .behind_by, merge_base: .merge_base_commit.sha}'
```

**One knock-on effect worth knowing about:** `.github/workflows/pr-health.yml` already has a `status: needs rebase` label, and it is gated on `mergeStateStatus == BEHIND`. That branch cannot be taken while `strict = false`, so the label has been silent since it was added in #933 back in June — no open PR carries it today, including the ones 13 commits behind. The repo's own drift signal is switched off by the same setting this issue is about.

The `reviewDecision` note in the description also still holds: no open PR reports an approval through the API today.

I have opened #3229 as a stopgap for the part that does not need admin rights: it drops the `BEHIND` dependency and computes drift from a ref comparison, labelling a PR only when it is behind *and* the base branch moved on files the PR also changes (3 of the 25 most recent open PRs, rather than the 18 of 20 that plain "behind by 1+" would catch). That only makes the risk visible on the PR — it does not gate the merge, so it is not a substitute for the acceptance criteria here. Enabling `required_status_checks.strict` or a merge queue on `main` still needs a maintainer.
